//go:generate go run ./gen

package mcp

import (
	"fmt"
	"reflect"
	"strings"
)

// tsInterfaces is the single source of truth mapping a TypeScript interface
// name (as used throughout vscode-acline/src/*.ts) to the Go struct whose
// JSON shape it must match. GenerateTypeScript renders this list into
// vscode-acline/src/generated.ts; TestGeneratedTypeScriptIsUpToDate
// (extension_types_test.go) fails the build if that file is stale.
//
// These interfaces are generated, not hand-typed, on the
// TypeScript side, so a renamed/added/removed Go field shows up as a
// generated-file diff instead of a silent runtime "undefined" (the failure
// mode TestExtensionInterfacesMatchServerResultFields used to catch after
// the fact, by parsing hand-written interface bodies out of mcpClient.ts and
// checking their fields were a subset of the Go struct's -- one-directional,
// and only caught fields already present. Generation removes the hand-write
// step entirely, so there's nothing left to drift).
var tsInterfaces = []struct {
	Name string
	Type reflect.Type
}{
	{"SearchHit", reflect.TypeFor[searchHitOut]()},
	{"MemoryEntry", reflect.TypeFor[memoryEntryOut]()},
	{"Task", reflect.TypeFor[taskOut]()},
	{"Decision", reflect.TypeFor[decisionOut]()},
	{"Spec", reflect.TypeFor[specOut]()},
	{"Criterion", reflect.TypeFor[criterionOut]()},
	{"Note", reflect.TypeFor[noteOut]()},
	{"Feature", reflect.TypeFor[featureOut]()},
	{"GateResult", reflect.TypeFor[taskGateOut]()},
	{"AuditEvent", reflect.TypeFor[eventOut]()},
	{"DashboardSession", reflect.TypeFor[sessionOut]()},
	{"Dashboard", reflect.TypeFor[dashboardOut]()},
	{"Metrics", reflect.TypeFor[metricsOut]()},
	{"VerifyResult", reflect.TypeFor[verifyOut]()},
	{"Project", reflect.TypeFor[projectOut]()},
	{"ProjectResolveResult", reflect.TypeFor[projectResolveOut]()},
	{"Check", reflect.TypeFor[checkOut]()},
	{"Dependency", reflect.TypeFor[dependencyOut]()},
	{"Role", reflect.TypeFor[roleOut]()},
	{"SessionDetail", reflect.TypeFor[sessionDetailOut]()},
	{"Eval", reflect.TypeFor[evalOut]()},
	{"Milestone", reflect.TypeFor[roadmapOut]()},
	{"ServerInfo", reflect.TypeFor[serverInfoOut]()},
	{"PolicyResult", reflect.TypeFor[policyShowOut]()},
	{"TaskRoute", reflect.TypeFor[taskRouteOut]()},
	{"CheckRunResult", reflect.TypeFor[checkRunOut]()},
	{"Plan", reflect.TypeFor[planOut]()},
	{"PlanItem", reflect.TypeFor[planItemOut]()},
	{"PlanShow", reflect.TypeFor[planShowOut]()},
	{"CreatedTask", reflect.TypeFor[createdTaskOut]()},
	{"PlanApproveResult", reflect.TypeFor[planApproveOut]()},
	{"TaskUpdateResult", reflect.TypeFor[taskUpdateOut]()},
	{"CheckRunner", reflect.TypeFor[checkRunnerOut]()},
	{"SpecVersion", reflect.TypeFor[specVersionOut]()},
	{"SpecShow", reflect.TypeFor[specShowOut]()},
}

// tsTypeNameFor reports the TypeScript interface name for a Go struct type
// registered in tsInterfaces, so a field whose type is (a slice/pointer of)
// one of these structs references that interface instead of an inlined
// anonymous shape.
func tsTypeNameFor(t reflect.Type) (string, bool) {
	for _, e := range tsInterfaces {
		if e.Type == t {
			return e.Name, true
		}
	}
	return "", false
}

// tsFieldType maps a Go field type to its TypeScript rendering. It panics on
// a Go kind with no established mapping, rather than guess -- a new field
// kind should extend this function deliberately, not fall through to
// something plausible-looking but wrong.
func tsFieldType(t reflect.Type) string {
	if name, ok := tsTypeNameFor(t); ok {
		return name
	}
	switch t.Kind() {
	case reflect.Pointer:
		return tsFieldType(t.Elem())
	case reflect.Slice, reflect.Array:
		return tsFieldType(t.Elem()) + "[]"
	case reflect.Map:
		return "Record<string, " + tsFieldType(t.Elem()) + ">"
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	default:
		panic(fmt.Sprintf("tsgen: no TypeScript mapping for %s (kind %s) -- extend tsFieldType", t, t.Kind()))
	}
}

// GenerateTypeScript renders every entry in tsInterfaces as a TypeScript
// interface, in Go struct field order, in the style mcpClient.ts already
// used by hand (2-space indent, `field?: type;` for an omitempty or pointer
// field, `field: type;` otherwise).
func GenerateTypeScript() string {
	var b strings.Builder
	b.WriteString("// Code generated by `go generate ./internal/mcp`. DO NOT EDIT.\n")
	b.WriteString("// Source of truth: the Go structs listed in internal/mcp/tsgen.go.\n")
	b.WriteString("// Regenerate after changing any MCP *Out struct: go generate ./internal/mcp\n")
	fmt.Fprintf(&b, "\n// The tool contract version this extension was built against (mcp.ProtocolVersion).\nexport const ACLINE_PROTOCOL_VERSION = %d;\n", ProtocolVersion)

	for _, e := range tsInterfaces {
		b.WriteString("\n")
		fmt.Fprintf(&b, "export interface %s {\n", e.Name)
		t := e.Type
		for i := 0; i < t.NumField(); i++ {
			f := t.Field(i)
			name, opts, _ := strings.Cut(f.Tag.Get("json"), ",")
			if name == "" || name == "-" {
				continue
			}
			// A field is optional in the generated TS type when Go omits it
			// (omitempty, or a pointer that's typically nil), or when it
			// carries an explicit ts:"optional" tag -- for a field this
			// binary always sends but that's absent from older servers, so
			// older-binary compatibility isn't lost by generating from the
			// current struct shape alone.
			optional := strings.Contains(opts, "omitempty") || f.Type.Kind() == reflect.Pointer || f.Tag.Get("ts") == "optional"
			mark := ""
			if optional {
				mark = "?"
			}
			fmt.Fprintf(&b, "  %s%s: %s;\n", name, mark, tsFieldType(f.Type))
		}
		b.WriteString("}\n")
	}
	return b.String()
}
