package store

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"acline/internal/clip"
	"acline/internal/untrusted"
)

// RenderContext writes the agent-facing context file (AGENTS.md / CLAUDE.md)
// from the database. The DB is the source; the markdown is a build
// artifact, which is what keeps it from drifting the way a hand-maintained
// instruction file does. This file is read at the start of every session, so
// density matters — tables and one-liners over prose, nothing said twice.
//
// vaultPath is optional (variadic so existing 2-arg callers keep compiling
// unchanged): when given and it contains SOUL.md/USER.md, their prose is
// folded in ahead of the DB-derived sections — the only content in this
// generated file that isn't sourced from the database, since identity and
// working preferences are genuinely unstructured, not decidable facts.
//
// projectID scopes every DB-derived section to one project (nil = every
// project, unscoped — the pre-project-scoping behavior). This matters:
// the store is shared across every tracked project, so without a scope
// here the file a session loads at start would mix every project's
// decisions/specs/memory/tasks/features together indiscriminately.
func (s *Store) RenderContext(w io.Writer, title string, projectID *int64, vaultPath ...string) error {
	return s.RenderContextLimited(w, title, projectID, 0, vaultPath...)
}

// RenderContextLimited is RenderContext with at most maxRows rows in each of
// the open-work and capabilities tables (0 = all); the rest are counted and
// pointed at. The SessionStart hook uses it: that text is loaded into every
// session, so it must not grow with the store.
func (s *Store) RenderContextLimited(w io.Writer, title string, projectID *int64, maxRows int, vaultPath ...string) error {
	if title == "" {
		title = "Project context"
	}
	fmt.Fprintf(w, "# %s\n\n", title)
	fmt.Fprintf(w, "<!-- generated by `acline context export` %s — do not hand-edit, regenerate instead -->\n\n",
		time.Now().UTC().Format("2006-01-02"))
	fmt.Fprintf(w, "%s\n\n", untrusted.Rule)

	if len(vaultPath) > 0 && vaultPath[0] != "" {
		s.renderVaultProse(w, vaultPath[0], projectID)
	}

	if err := s.renderConstraints(w, projectID); err != nil {
		return err
	}
	if err := s.renderDecisions(w, projectID); err != nil {
		return err
	}
	if err := s.renderSpecs(w, projectID); err != nil {
		return err
	}
	if err := s.renderCapabilities(w, projectID, maxRows); err != nil {
		return err
	}
	if err := s.renderOpenWork(w, projectID, maxRows); err != nil {
		return err
	}
	return nil
}

// Constraints come first: they are the rules that change what an agent may do,
// so they must land before anything descriptive.
func (s *Store) renderConstraints(w io.Writer, projectID *int64) error {
	mem, err := s.ListMemory(MemoryFilter{Status: "approved", ProjectID: projectID})
	if err != nil {
		return err
	}
	var constraints, lessons []MemoryEntry
	for _, m := range mem {
		if m.Kind == "constraint" {
			constraints = append(constraints, m)
		} else {
			lessons = append(lessons, m)
		}
	}

	if len(constraints) > 0 {
		fmt.Fprintf(w, "## Constraints\n\n")
		for _, m := range constraints {
			if m.Area.Valid && m.Area.String != "" {
				fmt.Fprintf(w, "- (%s) %s\n", m.Area.String, m.Body)
			} else {
				fmt.Fprintf(w, "- %s\n", m.Body)
			}
		}
		fmt.Fprintln(w)
	}
	if len(lessons) > 0 {
		fmt.Fprintf(w, "## Pitfalls\n\n")
		for _, m := range lessons {
			if m.Area.Valid && m.Area.String != "" {
				fmt.Fprintf(w, "- **%s** (%s): %s\n", m.Kind, m.Area.String, m.Body)
			} else {
				fmt.Fprintf(w, "- **%s**: %s\n", m.Kind, m.Body)
			}
		}
		fmt.Fprintln(w)
	}
	return nil
}

func (s *Store) renderDecisions(w io.Writer, projectID *int64) error {
	decisions, err := s.ListDecisions("accepted", projectID)
	if err != nil {
		return err
	}
	if len(decisions) == 0 {
		return nil
	}
	fmt.Fprintf(w, "## Accepted decisions\n\n")
	for _, d := range decisions {
		fmt.Fprintf(w, "**ADR-%d** %s", d.ID, d.Title)
		if d.Scope.Valid {
			fmt.Fprintf(w, " (%s)", d.Scope.String)
		}
		fmt.Fprintln(w)
		if d.DecisionText.Valid {
			fmt.Fprintf(w, "%s ", d.DecisionText.String)
		}
		if d.Rationale.Valid {
			fmt.Fprintf(w, "**Why:** %s", d.Rationale.String)
		}
		fmt.Fprintf(w, "\n\n")
	}
	return nil
}

func (s *Store) renderSpecs(w io.Writer, projectID *int64) error {
	specs, err := s.ListSpecs("approved", projectID)
	if err != nil {
		return err
	}
	if len(specs) == 0 {
		return nil
	}
	fmt.Fprintf(w, "## Approved specs\n\n")
	for _, sp := range specs {
		fmt.Fprintf(w, "**Spec %d** (v%d) %s\n", sp.ID, sp.Version, sp.Title)
		if sp.Body.Valid {
			fmt.Fprintf(w, "%s\n", sp.Body.String)
		}
		fmt.Fprintln(w)
	}
	return nil
}

// renderCapabilities and renderOpenWork list text anyone may record (a task
// title needs no approval), so unlike the person-approved sections above they
// are fenced as data (internal/untrusted): a planted title must not read as an
// instruction to the session that loads this file.
func (s *Store) renderCapabilities(w io.Writer, projectID *int64, maxRows int) error {
	features, err := s.ListFeatures("", projectID)
	if err != nil {
		return err
	}
	if len(features) == 0 {
		return nil
	}
	var b strings.Builder
	b.WriteString("| Name | Status | Owner | Source |\n|---|---|---|---|\n")
	shown := features
	if maxRows > 0 && len(shown) > maxRows {
		shown = shown[:maxRows]
	}
	for _, f := range shown {
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n",
			f.Name, f.Status, f.OwnerArea.String, f.SourcePointer.String)
	}
	fmt.Fprintf(w, "## Capabilities\n\n%s\n", untrusted.Quote("Capabilities", b.String()))
	if more := len(features) - len(shown); more > 0 {
		fmt.Fprintf(w, "\n…and %d more: `acline feature list`.\n", more)
	}
	fmt.Fprintf(w, "\n`n_a` = deliberately not built.\n\n")
	return nil
}

func (s *Store) renderOpenWork(w io.Writer, projectID *int64, maxRows int) error {
	tasks, err := s.ListTasks(TaskFilter{ProjectID: projectID})
	if err != nil {
		return err
	}
	if len(tasks) == 0 {
		return nil
	}
	var b strings.Builder
	b.WriteString("| # | Status | Prio | Risk | Autonomy | Title |\n|---|---|---|---|---|---|\n")
	shown := tasks // ListTasks orders by priority, so the cut keeps the urgent ones
	if maxRows > 0 && len(shown) > maxRows {
		shown = shown[:maxRows]
	}
	for _, t := range shown {
		title := t.Title
		if t.Deferred {
			title += " (deferred)"
		}
		fmt.Fprintf(&b, "| %d | %s | %s | %s | %s | %s |\n",
			t.ID, t.Status, t.Priority, t.Risk, t.Autonomy, title)
	}
	fmt.Fprintf(w, "## Open work\n\n%s\n", untrusted.Quote("Open work (task titles)", b.String()))
	if more := len(tasks) - len(shown); more > 0 {
		fmt.Fprintf(w, "\n…and %d more open task(s): `acline task list`.\n", more)
	}
	fmt.Fprintf(w, "\nrisk=high/critical or autonomy=hitl needs a recorded approval to complete.\n")
	return nil
}

// renderVaultProse folds SOUL.md/USER.md into the generated context, if
// present. Best-effort: a missing vault or missing files are silently
// skipped rather than failing the export.
// renderVaultProse folds in SOUL.md/USER.md verbatim, then, if a role is
// active for this invocation (see Store.ResolveRole) and that role has a
// persona file at vault/roles/<name>.md, folds that in too as one more
// "## Role: <name>" section. No active role, or no matching file, leaves
// the output byte-identical to before roles existed (acline spec #2).
func (s *Store) renderVaultProse(w io.Writer, vaultPath string, projectID *int64) {
	for _, name := range []string{"SOUL.md", "USER.md"} {
		b, err := os.ReadFile(filepath.Join(vaultPath, name))
		if err != nil || len(b) == 0 {
			continue
		}
		fmt.Fprintf(w, "## %s\n\n%s\n\n", name, strings.TrimSpace(clip.WithoutFrontMatter(string(b))))
	}

	roleID, err := s.ResolveRole("", projectID)
	if err != nil || roleID == nil {
		return
	}
	role, err := s.GetRole(*roleID)
	if err != nil {
		return
	}
	b, err := os.ReadFile(filepath.Join(vaultPath, "roles", role.Name+".md"))
	if err != nil || len(b) == 0 {
		return
	}
	fmt.Fprintf(w, "## Role: %s\n\n%s\n\n", role.Name, strings.TrimSpace(clip.WithoutFrontMatter(string(b))))
}
