package scaffold

import (
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"strings"
)

// A Claude Code plugin carries acline's skills and agents as one versioned
// unit, so they stop drifting between repos that each got a copy from
// `acline init`. It deliberately carries no hooks and no settings: a plugin's
// settings.json honours only `agent` and `subagentStatusLine`, so the
// permissions.deny rules and the ACLINE_ACTOR_TYPE=agent environment that the
// guard relies on can only come from the project's .claude/settings.json.
// Hooks stay there too, next to them, so a guard never runs without its deny
// layer and the orchestrator's preflight (which reads project settings) keeps
// working. Hooks in both places would also run twice.

// PluginOptions controls ExportPlugin.
type PluginOptions struct {
	Version string // plugin.json version (the acline build's)
	WithMCP bool   // also write .mcp.json registering `acline mcp serve --as agent`
	Force   bool   // write into a non-empty directory
}

// ErrPluginDirNotEmpty is returned when dir has files and Force is not set.
var ErrPluginDirNotEmpty = errors.New("the plugin directory is not empty; choose an empty one or pass --force to overwrite acline's files in it")

// ExportPlugin writes a Claude Code plugin to dir and returns the files written.
func ExportPlugin(dir string, opts PluginOptions) ([]string, error) {
	if entries, err := os.ReadDir(dir); err == nil && len(entries) > 0 && !opts.Force {
		return nil, ErrPluginDirNotEmpty
	} else if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return nil, err
	}
	var written []string
	write := func(rel string, data []byte) error {
		target := filepath.Join(dir, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(target, data, 0o644); err != nil {
			return err
		}
		written = append(written, rel)
		return nil
	}

	version := strings.TrimPrefix(opts.Version, "v")
	if version == "" || version == "dev" {
		version = "0.0.0-dev"
	}
	manifest, _ := json.MarshalIndent(map[string]any{
		"name":        "acline",
		"displayName": "acline",
		"version":     version,
		"description": "acline's skills and agents: specs, tasks, the completion gate and the audit trail, driven by the acline CLI. Run `acline init` in each project for the guard hooks and safety settings.",
		"author":      map[string]string{"name": "ows4444"},
		"repository":  "https://github.com/ows4444/acline",
		"license":     "MIT",
		"keywords":    []string{"sdlc", "verification", "audit"},
	}, "", "  ")
	if err := write(".claude-plugin/plugin.json", append(manifest, '\n')); err != nil {
		return nil, err
	}

	for _, sub := range []string{"skills", "agents"} {
		err := fs.WalkDir(assets, path.Join("assets", sub), func(p string, d fs.DirEntry, err error) error {
			if err != nil || d.IsDir() {
				return err
			}
			data, err := assets.ReadFile(p)
			if err != nil {
				return err
			}
			return write(strings.TrimPrefix(p, "assets/"), data)
		})
		if err != nil {
			return nil, err
		}
	}

	if opts.WithMCP {
		mcp, _ := json.MarshalIndent(map[string]any{
			"mcpServers": map[string]any{
				"acline": map[string]any{
					"command": "acline",
					"args":    []string{"mcp", "serve", "--as", "agent"},
					"env":     map[string]string{"ACLINE_ACTOR_TYPE": "agent", "ACLINE_ACTOR": "claude-code"},
				},
			},
		}, "", "  ")
		if err := write(".mcp.json", append(mcp, '\n')); err != nil {
			return nil, err
		}
	}

	readme := fmt.Sprintf(`# acline plugin %s

Generated by `+"`acline plugin export`"+`. It carries acline's skills (as `+"`/acline:<skill>`"+`) and its role agents.

It does **not** carry the guard hooks, the permissions.deny rules or the agent identity environment: a plugin cannot set those. Run `+"`acline init`"+` in each project for them; the orchestrator refuses to launch where the project's guard hook is missing.

Load it with `+"`claude --plugin-dir <this directory>`"+`, or add the directory to a plugin marketplace. Regenerate it after upgrading acline.
`, version)
	if err := write("README.md", []byte(readme)); err != nil {
		return nil, err
	}
	return written, nil
}
